[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "load-clean"
version = "0.0.1"
description = "Python package"
requires-python = ">=3.10"

dependencies = [
    "ipython",
    "ast-comments",
    "pytest>=9.1.1",
]

[project.optional-dependencies]
tools = [
    "jupytext>=1.19.5",
    "nbformat>=5.11.0",
]

[project.scripts]
load-clean-build = "load_clean_tools.cli:main"

[tool.setuptools.packages.find]
where = [
    "src"
]

[dependency-groups]
dev = [
    "build>=1.5.0",
    "pytest>=8.0.0",
]
